//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurenceApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmergencyApplication()
        {
            this.PhotoEmergency = new HashSet<PhotoEmergency>();
        }
    
        public int Id { get; set; }
        public int DriverId { get; set; }
        public int CarId { get; set; }
        public System.DateTime DateEmergency { get; set; }
        public int StatusId { get; set; }
        public double Price { get; set; }
        public int ApplicationType { get; set; }
    
        [JsonIgnore]
        public virtual Car Car { get; set; }
        [JsonIgnore]
        public virtual Driver Driver { get; set; }
        [JsonIgnore]
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoEmergency> PhotoEmergency { get; set; }
    }
}
