//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurenceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insurence()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public int UserId { get; set; }
        public int InsurenceTypeId { get; set; }
        public System.DateTime DateUntil { get; set; }
        public int CarId { get; set; }
    
        public virtual InsurenceType InsurenceType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
