//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurenceApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoEmergency
    {
        public int Id { get; set; }
        public int EmergencyApplicationId { get; set; }
        public byte[] Photo { get; set; }
    
        [JsonIgnore]
        public virtual EmergencyApplication EmergencyApplication { get; set; }
    }
}
