//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsurenceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int InsurenceId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Insurence Insurence { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
    }
}
